<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <?php echo $this->headTitle('ZF2 '. $this->translate('AviaSG todo testas'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->setCharset('UTF-8');
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->appendFile('https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js','text/javascript')
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/moment.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
            ->appendFile($this->basePath('/js/main.js'))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <!-- <img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/> -->
                        &nbsp;<?php echo $this->translate('Todo application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php
                   if(!$this->zfcUserIdentity()): ?>   
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="<?php  echo $this->url('zfcuser/login') ?>"><?php  echo $this->translate('Register/Login') ?></a>
                        </li>
                    </ul>
                    <?php else:  
                    echo $this->navigation('navigation')
                                ->menu()
                                ->setMinDepth(0)
                                ->setMaxDepth(0)
                                ->setUlClass('nav navbar-nav');
                    
                    endif
                     /*
                    <!-- <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php // echo $this->url('home') ?>"><?php // echo $this->translate('Home') ?></a></li>
                    </ul> -->
                    */?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>               
                <p class="pull-right">   &copy; by Artūras Sotničenko <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
