
<?php if(!$this->zfcUserIdentity()):
	 echo $this->zfcUserLoginWidget(array('redirect'=>'application'));
  else:
 if($this->zfcUserIdentity()->getState() == 1): ?>
  
  <div class="users">
  	<h2>Registered Users</h2>
  	<?php foreach ($users as $user): ?>
  	<div class="row">
  		<?php  echo $user->getUsername(); ?>
  	</div>
  	<?php endforeach ?>
  </div>
<?php else: ?>
    <!-- display the 'display name' of the user -->
    <?php echo "not authorized"; ?>
<?php endif?>
<?php endif?>