<?php if(!$this->zfcUserIdentity()): ?>
    <!-- display the login form -->
    <?php echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
<?php else: ?>
    <!-- display the 'display name' of the user -->
    <?php echo $this->zfcUserIdentity()->getDisplayname();
          echo $this->zfcUserIdentity()->getEmail();
           echo $this->zfcUserIdentity()->getState(); ?>
<?php endif?>