<div id="login">


<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>
<div class="container">
    <?php echo $this->form()->openTag($form) ?>

  <div class="login zend_form">
  <h1><?php echo $this->translate('Sign In'); ?></h1>     
    <div class="login-form">

      <div class="username-row row">
     
        <?php echo $this->formElementErrors($form->get('identity')) ?>
        <?php echo $this->formLabel($form->get('identity')) ?>
        <?php echo $this->formInput($form->get('identity')) ?>
    </div>
     <div class="password-row row">
        <?php echo $this->formLabel($form->get('credential')) ?>
        <?php echo $this->formInput($form->get('credential')) ?>

        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

     
      </div>
    </div>

    <div class="call-to-action">
      <?php echo $this->formButton($form->get('submit')) ?>
      <?php if ($this->enableRegistration) : ?>
      <p>Don't have an account? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>"><?php echo $this->translate('Sign up!'); ?></a></p>
      <?php endif; ?>
      <?php echo $this->form()->closeTag() ?>
    </div>
  </div>
</div>
</div>

