<div id="login">
<h1><?php echo $this->translate('Register'); ?></h1>

<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>
<div class="container">
<?php echo $this->form()->openTag($form) ?>
    <div class="login zend_form">
    <?php foreach ($form as $element): ?>
    <div class="username-row row">
        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <?php echo $this->formLabel($element) ?>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <?php echo $this->formButton($element) ?>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
        <?php else: ?>
            <?php echo $this->formInput($element) . $this->formElementErrors($element) ?>
        <?php endif ?>
    </div>
    <?php endforeach ?>
    
    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
    <?php endif ?>
    </div> 
<?php echo $this->form()->closeTag() ?>
</div>
</div>