<center><h1>Todo List</h1></center>
<div class="content">
 <div class="header"> 
        <div class="row">
          <div class="input-group">   
          <textarea  type="text" class="todo-input" placeholder="Add todo here!"></textarea >            
          <span class="input-group-addon">
            <button type="submit" class="glyphicon glyphicon-plus input-group-btn create-todo"></button>
          </span>
          </div>
        </div>
        <div class="row">
          <div class='col-md-6 pull-left input-group date' id='dtp'>
              <input type='text' class="due" placeholder="Due.." >
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </input> 
          </div>    
          <span class="pull-left">Priority:
          <select class="priority selectpicker">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>
            <option>7</option>
            <option>8</option>
            <option>9</option>
          </select>
          </span> 
      </div>         
 </div>

 <div class="todos">
    <?php foreach($todos as $todo):?>
    <div class="row todoItem <?php if ($todo->getCompleted() == 1) {  echo 'done';  } ?>">
       <span  id="todo-<?php echo $todo->getId() ?>" class="todo" contenteditable="true"><?php echo $todo->getTodo()?></span>
        <div class="row">
        <button  id="remove-<?php echo $todo->getId(); ?>" class="delete-todo">
          <span class="entypo-cancel"></span>
        </button>
       <?php if ($todo->getDeadline() !== "0000-00-00 00:00:00" ) { ?>
         <span contenteditable="true" id="deadline-<?php echo $todo->getId() ?>" class="deadline  label label-default pull-right"><?php echo substr($todo->getDeadline(), 0, -3); ?></span>
       <?php } ?> 
        
       <span class="label label-default priority priority-<?php echo $todo->getPriority()?> pull-right">Priority: <?php echo $todo->getPriority()?></span>       
        <button class="check-todo">
          <span class="entypo-check"></span>
        </button>
        </div>
    </div>

    <?php endforeach; ?>
 
            
     
</div>
<div class="clear-both"></div> 
</div>
<?php /*<div ng-app="todo" ng-controller="toDoCtrl">
  <div class="content">
    <div class="header">
      <form action="">
     
        <button type="submit" ng-click="getTodos()">
          <span class="entypo-list-add"></span>
        </button>
      <input type="text" ng-model="todoFld" placeholder="Add todo here!"/>
      </form>      
    </div>    
    <div class="todoItem" ng-repeat="todo in todos">
      <li>
      <span class="{{todo.done}}{{todo.id}}" contenteditable="true">{{todo.todo}}</span>
      <button  ng-click="removeTodo(todo.id)">
        <span class="entypo-cancel"></span>
      </button>
      <button ng-click="doneTodo($index)">
        <span class="entypo-check"></span>
      </button>
      </li>
    </ul>
  </div>*/
  ?>