<center><h1>Todo List</h1></center>
<div class="content">
 <div class="header"> 
        <div class="row">
          <div class="input-group">   
          <textarea  type="text" class="todo-input" placeholder="Add todo here!"></textarea >            
          
          </div>
        </div>
        <div class="row">
          <div class='col-md-6 pull-left input-group date' id='dtp'>
              <input type='text' class="due" placeholder="Due.." >
              <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </input> 
          </div>    
          <span class="pull-left">Priority:
          <select class="priority selectpicker">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>
            <option>7</option>
            <option>8</option>
            <option>9</option>
          </select>
          </span> 
          <span class="input-group-addon">
            <button type="submit" class="glyphicon glyphicon-plus input-group-btn create-todo"><span class="add"> Add!</span></button>
          </span>
      </div>         
 </div>
 <div role="tabpanel">

  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#todos" aria-controls="todos" role="tab" data-toggle="tab">All todos</a></li>
    <li role="presentation"><a href="#Todays" aria-controls="profile" role="tab" data-toggle="tab">Todays todo</a></li>
    <li role="presentation"><a href="#Priority" aria-controls="messages" role="tab" data-toggle="tab">Priority rank</a></li>
  </ul>

  <!-- Tab panes -->
  

</div>
<div class="tab-content">
  <div role="tabpanel" class="tab-pane fade in active" id="todos">
   <div class="todos">
    <?php foreach($todos as $todo):?>
      <?php echo $this->partial('todos/partials/todo-partial.phtml', array('todo' => $todo)); ?>
    <?php endforeach; ?> 
     
  </div>
   <button class="center-block btn btn-defoult load-more">LOAD MORE TODOS</button> 
</div>
<div role="tabpanel" class="fade tab-pane" id="Todays">
  <div class="todos">
<?php foreach($todos as $todo): ?>
 <?php $todoDate  = new DateTime($todo->getDeadline());
       $today     = new DateTime();
 if ($todoDate->diff($today)->days === 0):  ?>
   <?php echo $this->partial('todos/partials/todo-partial.phtml', array('todo' => $todo)); ?>
   <?php endif; ?> 
  <?php endforeach; ?>
  
</div>
<button class="center-block btn btn-defoult load-more">LOAD MORE TODOS</button>
</div>

<div role="tabpanel" class="fade tab-pane" id="Priority">
  <div class="todos">
<?php foreach($PriorityTodos as $todo): ?>
   <?php echo $this->partial('todos/partials/todo-partial.phtml', array('todo' => $todo)); ?>  
  <?php endforeach; ?>
  
</div>
<button class="center-block btn btn-defoult load-more">LOAD MORE TODOS</button>
</div>

</div>
<div class="clear-both"></div> 
</div>
<?php /*<div ng-app="todo" ng-controller="toDoCtrl">
  <div class="content">
    <div class="header">
      <form action="">
     
        <button type="submit" ng-click="getTodos()">
          <span class="entypo-list-add"></span>
        </button>
      <input type="text" ng-model="todoFld" placeholder="Add todo here!"/>
      </form>      
    </div>    
    <div class="todoItem" ng-repeat="todo in todos">
      <li>
      <span class="{{todo.done}}{{todo.id}}" contenteditable="true">{{todo.todo}}</span>
      <button  ng-click="removeTodo(todo.id)">
        <span class="entypo-cancel"></span>
      </button>
      <button ng-click="doneTodo($index)">
        <span class="entypo-check"></span>
      </button>
      </li>
    </ul>
  </div>*/
  ?>